### ISSUE TITLE
Unicode bug

### ISSUE THREAD

**Issue by Bystroushaak** [edeposit/edeposit.amqp.ltp#18]
There is unicode bug for ISBN 80-86056-31-7.

**Comment by Bystroushaak** [comment]
```Traceback (most recent call last):
  File "./generate_example.py", line 45, in <module>
    b64_data
  File "/home/bystrousak/Plocha/prace/edeposit.amqp.ltp/src/edeposit/amqp/ltp/ltp.py", line 360, in create_ltp_package
    aleph_record=aleph_record,
  File "/home/bystrousak/Plocha/prace/edeposit.amqp.ltp/src/edeposit/amqp/ltp/ltp.py", line 298, in _compose_info
    xml_document = xmltodict.unparse(document, pretty=True)
  File "/usr/local/lib/python2.7/dist-packages/xmltodict.py", line 329, in unparse
    _emit(key, value, content_handler, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/xmltodict.py", line 295, in _emit
    pretty, newl, indent)
  File "/usr/local/lib/python2.7/dist-packages/xmltodict.py", line 273, in _emit
    v = _unicode(v)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
```
