### ISSUE TITLE
error when installing module structures

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.ltp#34]
edeposit-aplikace:/opt/edeposit # edeposit_amqp_ltpd.py start --foreground
Traceback (most recent call last):
  File "/usr/bin/edeposit_amqp_ltpd.py", line 20, in <module>
    from edeposit.amqp.ltp.structures import *
ImportError: No module named structures
edeposit-aplikace:/opt/edeposit # pip install -U structures
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting structures
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading structures-2.0.2.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-mqHuZg/structures/setup.py", line 6, in <module>
        from structures import __version__
      File "structures/__init__.py", line 3, in <module>
        from .structure import *
      File "structures/structure.py", line 82
        class Structure(object, metaclass=StructureMetaClass):
                                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mqHuZg/structures
edeposit-aplikace:/opt/edeposit #

**Comment by jstavel** [comment]
is is fixed now. Closing.
